- name: Copy environment file to the server
  copy:
    src: ./prod.env
    dest: /home/{{ ansible_user }}/app/prod.env
    mode: '0644'

- name: Create nmeaFiles directory
  file:
    path: /home/{{ ansible_user }}/app/server/src/nmeaFiles/
    state: directory
    mode: '0755'

- name: Create nginx conf directory
  file:
    path: /home/{{ ansible_user }}/app/nginx/
    state: directory
    mode: '0755'

- name: Copy nmeaFile to server
  copy:
    src: ./files/leixoes_campanha.txt
    dest: /home/{{ ansible_user }}/app/server/src/nmeaFiles/leixoes_campanha.txt

- name: Copy nginx conf to server
  copy:
    src: ./files/nginx.conf
    dest: /home/{{ ansible_user }}/app/nginx/nginx.conf

# - name: Restart Nginx
#   service:
#     name: nginx
#     state: restarted

- name: Copy Docker Compose file to the server
  copy:
    src: ./files/compose.yaml
    dest: /home/{{ ansible_user }}/app/compose.yaml
    mode: '0644'
