services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    expose:
      - 4173
    networks:
      - private
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - 3000
    networks:
      - private
    volumes:
      - ./server/src/nmeaFiles/leixoes_campanha.txt:/app/src/nmeaFiles/leixoes_campanha.txt:ro

  nginx:
    image: nginx:stable-alpine3.19-perl
    ports:
      - '8080:80'
    networks:
      - private
      - public
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

networks:
  public:
    driver: bridge
  private:
    driver: bridge
