- name: Save Docker images locally
  hosts: localhost
  tasks:
    - name: Save frontend Docker image
      command: docker save -o frontend.tar train-journey-simulator-frontend 

    - name: Save backend Docker image
      command: docker save -o backend.tar train-journey-simulator-backend 

    - name: Save nginx Docker image
      command: docker save -o nginx.tar nginx