- name: Include tasks for installing Docker and Docker Compose
  include_tasks: install-docker.yaml

- name: Include tasks for loading Docker images
  include_tasks: load-images.yaml

- name: Include tasks for running docker container
  include_tasks: run-container.yaml
