- name: Create app directory
  file:
    path: /home/{{ ansible_user }}/app/
    state: directory
    mode: '0755'

- name: Update and upgrade all packages to the latest version
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
