services:
  frontend:
    image: train-journey-simulator-frontend
    expose:
      - 4173
    networks:
      - private
    env_file:
      - 'prod.env'
    environment:
      - VITE_SERVER_URL
      - SERVER_PATH
    depends_on:
      - backend

  backend:
    image: train-journey-simulator-backend
    expose:
      - 3000
    networks:
      - private
    volumes:
      - ./components/server/src/nmeaFiles/leixoes_campanha.txt:/app/src/nmeaFiles/leixoes_campanha.txt:ro
    env_file:
      - 'prod.env'
    environment:
      - SERVER_PATH
      - SERVER_PORT

  nginx:
    image: nginx:stable-alpine3.19-perl
    ports:
      - '8080:80'
    networks:
      - private
      - public
    volumes:
      - ./infra/playbooks/roles/reverse-proxy/files/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

networks:
  public:
    driver: bridge
  private:
    driver: bridge
