services:
  frontend:
    image: client:latest
    expose:
      - 4173
    networks:
      - private
    env_file:
      - 'prod.env'
    environment:
      - VITE_SERVER_URL
      - SERVER_PATH
    depends_on:
      - backend

  backend:
    image: server:latest
    expose:
      - 3000
    networks:
      - private
    volumes:
      - ./data/server/nmea-files/leixoes-campanha.txt:/app/src/nmeaFiles/leixoes_campanha.txt:ro
    env_file:
      - 'prod.env'
    environment:
      - SERVER_PATH
      - SERVER_PORT

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    networks:
      - private
      - public
    volumes:
      - ./data/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

networks:
  public:
    driver: bridge
  private:
    driver: bridge
